# Generated by Django 4.0.6 on 2022-08-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=12)),
                ('District', models.CharField(max_length=20)),
                ('Taluka', models.CharField(max_length=20)),
                ('Village', models.CharField(max_length=20)),
                ('soil_hecter', models.CharField(max_length=20)),
                ('document_7_12_8', models.CharField(max_length=20)),
                ('Application_Number', models.CharField(max_length=20)),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=8)),
                ('Confirm_Password', models.CharField(max_length=8)),
            ],
        ),
    ]
