# Generated by Django 4.1 on 2022-09-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_remove_registration_application_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=12)),
                ('Password', models.CharField(max_length=8)),
                ('District', models.CharField(max_length=20)),
                ('Taluka', models.CharField(max_length=20)),
                ('Village', models.CharField(max_length=20)),
                ('soil_hecter', models.CharField(max_length=20)),
                ('servay_num', models.CharField(max_length=10)),
                ('document_7_12_8', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='registration',
        ),
    ]
