# Generated by Django 4.1 on 2022-09-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_reg_model_delete_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_model',
            name='document_7_12_8',
            field=models.ImageField(upload_to='images'),
        ),
    ]
