# Generated by Django 4.1 on 2022-09-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_reg_model_document_7_12_8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_model',
            name='document_7_12_8',
            field=models.CharField(max_length=20),
        ),
    ]
