# Generated by Django 4.0.5 on 2022-09-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_alter_reg_model_document_7_12_8'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg_model',
        ),
    ]
