# Generated by Django 4.0.5 on 2022-09-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_schemes_schemes_desc_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
