# Generated by Django 4.0.5 on 2022-09-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='Schemes_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schemes_status',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
