# Generated by Django 4.0.5 on 2022-10-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_alter_schemes_schemes_id_alter_schemes_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes_status',
            name='Schemes_status',
            field=models.CharField(max_length=50),
        ),
    ]
