# Generated by Django 4.0.5 on 2022-10-14 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_remove_schemes_status_farmer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied_Schemes',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Schemes_status', models.CharField(max_length=50)),
                ('Farmer_Adhar_Card', models.CharField(max_length=16)),
                ('Farmer_Bank_Name', models.CharField(max_length=50)),
                ('Farmer_Bank_IFSC', models.CharField(max_length=10)),
                ('Farmer_Account_num', models.CharField(max_length=15)),
                ('Farmer_Mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.user')),
                ('Scheme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.schemes')),
            ],
        ),
        migrations.DeleteModel(
            name='Schemes_Status',
        ),
    ]
