# Generated by Django 4.0.5 on 2022-10-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_applied_schemes_delete_schemes_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applied_schemes',
            old_name='Scheme_id',
            new_name='Sch',
        ),
        migrations.RenameField(
            model_name='applied_schemes',
            old_name='Farmer_Mobile',
            new_name='Usr',
        ),
    ]
